[CHANGE] sale_order, create_sale_order_wizard: now allow you cancel S…
Jarsa/sale-workflow pull request #28
Opened 2020-03-27 23:13 UTC by jesus01x

…O and Again create it.

2020-03-27 23:14 UTC, jesus01x commented
@alan196

2020-03-30 15:04 UTC, alan196 requested changes

2020-03-30 15:04 UTC, alan196 commented on sale_request/wizards/create_sale_order_wizard.py
> +        if not orders:
con lo que hiciste este IF siempre va a dar verdadero.

Entonces siempre va a crear una SO, esto crearía muchísimas SO, prácticamente una SO por cada línea de producto.

Esta no es una solución

2020-03-30 15:04 UTC, alan196 commented on sale_request/wizards/create_sale_order_wizard.py
> +                ('request_line_id', '=', self.request_line_id.id)], limit=1)
en vez de hacer un limit=1 (que haría muchas inconsistencias) lo ideal sería filtrar que el estado de la SO no sea cancelado.

2020-03-30 15:04 UTC, alan196 commented on sale_request/wizards/create_sale_order_wizard.py
> +            if sale_line and sale_line.state != 'cancel':
Si filtras en el dominio de arriba esta validación no tiene que hacerse

2020-03-30 15:04 UTC, alan196 commented on sale_request/models/sale_order.py
> +                request_lines.state = 'pending'
aquí si es más de un `request_lines` va a darte un expected singleton.

Usa request_lines.write({'state': 'pending'})

2020-03-30 15:04 UTC, alan196 commented on sale_request/models/sale_order.py
> +                rec.request_id.state = 'draft'
```python
if rec.request_id.state == 'done':
    rec.request_id.state == 'confirm'
```

2020-03-30 17:47 UTC, merged